In [5]:
from IPython.display import display
import pandas as pd

months = ["Січ", "Лют", "Бер", "Кві", "Тра", "Чер", "Лип", "Сер", "Вер", "Жов", "Лис", "Гру"]
avg_temp = [-3.5, -2.5, 2.0, 9.5, 15.5, 19.0, 21.0, 20.0, 14.5, 8.5, 2.5, -2.0]
precip = [38, 36, 38, 41, 53, 74, 84, 69, 47, 36, 44, 44]

df = pd.DataFrame({
    "month": months,
    "avg_temp": avg_temp,
    "precip": precip,
})

print("--- Перші 5 рядків ---")
display(df.head())

print("\n--- Розмір DataFrame ---")
print(df.shape)

print("\n--- Типи даних ---")
print(df.dtypes)

--- Перші 5 рядків ---

  month  avg_temp  precip
0   Січ      -3.5      38
1   Лют      -2.5      36
2   Бер       2.0      38
3   Кві       9.5      41
4   Тра      15.5      53

--- Розмір DataFrame ---
(12, 3)

--- Типи даних ---
month           str
avg_temp    float64
precip        int64
dtype: object

In [8]:
print("--- Початковий індекс (df.index) ---")
print(df.index)
display(df)

df_by_month = df.set_index("month")
print("\n--- Рядок для червня ('Чер') за допомогою .loc ---")
display(df_by_month.loc["Чер"])

df_by_month.reset_index(inplace=True)
print("\n--- Таблиця після reset_index ---")
display(df_by_month)

--- Початковий індекс (df.index) ---
RangeIndex(start=0, stop=12, step=1)

   month  avg_temp  precip
0    Січ      -3.5      38
1    Лют      -2.5      36
2    Бер       2.0      38
3    Кві       9.5      41
4    Тра      15.5      53
5    Чер      19.0      74
6    Лип      21.0      84
7    Сер      20.0      69
8    Вер      14.5      47
9    Жов       8.5      36
10   Лис       2.5      44
11   Гру      -2.0      44

--- Рядок для червня ('Чер') за допомогою .loc ---

avg_temp    19.0
precip      74.0
Name: Чер, dtype: float64

--- Таблиця після reset_index ---

   month  avg_temp  precip
0    Січ      -3.5      38
1    Лют      -2.5      36
2    Бер       2.0      38
3    Кві       9.5      41
4    Тра      15.5      53
5    Чер      19.0      74
6    Лип      21.0      84
7    Сер      20.0      69
8    Вер      14.5      47
9    Жов       8.5      36
10   Лис       2.5      44
11   Гру      -2.0      44

In [9]:
df.index = range(1, 13)
print("--- Стовпець avg_temp для місяців із підписом від 1 до 6 (.loc) ---")
display(df.loc[1:6, "avg_temp"])

print("\n--- Стовпець avg_temp за позиціями 0..5 (.iloc) ---")
display(df.iloc[0:6, df.columns.get_loc("avg_temp")])

print("\n--- Лише стовпці month та precip ---")
display(df[["month", "precip"]])

--- Стовпець avg_temp для місяців із підписом від 1 до 6 (.loc) ---

1    -3.5
2    -2.5
3     2.0
4     9.5
5    15.5
6    19.0
Name: avg_temp, dtype: float64

--- Стовпець avg_temp за позиціями 0..5 (.iloc) ---

1    -3.5
2    -2.5
3     2.0
4     9.5
5    15.5
6    19.0
Name: avg_temp, dtype: float64

--- Лише стовпці month та precip ---

   month  precip
1    Січ      38
2    Лют      36
3    Бер      38
4    Кві      41
5    Тра      53
6    Чер      74
7    Лип      84
8    Сер      69
9    Вер      47
10   Жов      36
11   Лис      44
12   Гру      44

In [10]:
print("--- Місяці, де avg_temp > 15 ---")
display(df[df["avg_temp"] > 15])

print("\n--- Місяці, де одночасно avg_temp > 10 і precip > 50 ---")
display(df[(df["avg_temp"] > 10) & (df["precip"] > 50)])

print("\n--- Місяці, де avg_temp < 0 або precip > 80 ---")
display(df[(df["avg_temp"] < 0) | (df["precip"] > 80)])

--- Місяці, де avg_temp > 15 ---

  month  avg_temp  precip
5   Тра      15.5      53
6   Чер      19.0      74
7   Лип      21.0      84
8   Сер      20.0      69

--- Місяці, де одночасно avg_temp > 10 і precip > 50 ---

  month  avg_temp  precip
5   Тра      15.5      53
6   Чер      19.0      74
7   Лип      21.0      84
8   Сер      20.0      69

--- Місяці, де avg_temp < 0 або precip > 80 ---

   month  avg_temp  precip
1    Січ      -3.5      38
2    Лют      -2.5      36
7    Лип      21.0      84
12   Гру      -2.0      44

In [11]:
df["avg_temp_f"] = df["avg_temp"] * 9/5 + 32

df["is_wet"] = df["precip"] > df["precip"].mean()

def get_season(month_num):
    if month_num in [12, 1, 2]:
        return "зима"
    elif month_num in [3, 4, 5]:
        return "весна"
    elif month_num in [6, 7, 8]:
        return "літо"
    else:
        return "осінь"

df["season"] = df.index.to_series().apply(get_season)

print("--- Підсумковий DataFrame з усіма обчислюваними стовпцями ---")
display(df)

--- Підсумковий DataFrame з усіма обчислюваними стовпцями ---

   month  avg_temp  precip  avg_temp_f  is_wet season
1    Січ      -3.5      38        25.7   False   зима
2    Лют      -2.5      36        27.5   False   зима
3    Бер       2.0      38        35.6   False  весна
4    Кві       9.5      41        49.1   False  весна
5    Тра      15.5      53        59.9    True  весна
6    Чер      19.0      74        66.2    True   літо
7    Лип      21.0      84        69.8    True   літо
8    Сер      20.0      69        68.0    True   літо
9    Вер      14.5      47        58.1   False  осінь
10   Жов       8.5      36        47.3   False  осінь
11   Лис       2.5      44        36.5   False  осінь
12   Гру      -2.0      44        28.4   False   зима

**Контролюючі запитання**

### Письмові відповіді на контрольні питання

1. **Чому `.loc[1:6]` і `.iloc[0:6]` можуть повернути різну кількість рядків, залежно від того, який саме індекс у таблиці?**
   * `.loc` працює за **підписами (мітками/labels)** індексу і включає **обидва кінці** вказаного діапазону. Наприклад, `.loc[1:6]` поверне всі рядки, які мають підписи від `1` до `6` включно (це 6 рядків, якщо індекс від 1 до 12). Якщо ж підписи текстові або довільні, `.loc[1:6]` може видати помилку або не знайти потрібні значення.
   * `.iloc` працює за **фізичними позиціями (індексами масиву)**, де зріз виконується за правилами Python (права межа **не включається**). Зріз `.iloc[0:6]` завжди поверне 6 рядків з позиціями 0, 1, 2, 3, 4 та 5, незалежно від того, якими є підписи у стовпці індексу.

2. **Чому `df["avg_temp"] > 10 and df["precip"] > 50` викличе помилку, а `(df["avg_temp"] > 10) & (df["precip"] > 50)` — ні?**
   * Стандартний оператор Python `and` очікує єдине булеве значення (`True` або `False`) для оцінки виразу. Спроба обчислити `and` для цілого об'єкта `pandas.Series` призводить до помилки `ValueError: The truth value of a Series is ambiguous`, оскільки pandas не знає, перевіряти увесь стовпець чи його частину.
   * Оператор `&` в pandas є побітовим/поелементним і спеціально перевантажений для того, щоб виконувати логічне "І" **для кожного елемента масиву окремо**, повертаючи новий булевий стовпець (`Series`). Дужки потрібні через те, що у Python оператор `&` має вищий пріоритет за операції порівняння (`>` чи `<`).

3. **У чому різниця між обчислюваним стовпцем, створеним формулою, і створеним через `.apply()`?**
   * **Створення формулою (векторизація):** Використовує внутрішньо оптимізовані масиви NumPy (С-рівень). Операція виконується одночасно над усім стовпцем (вектором) без використання явних циклів Python, що забезпечує максимальну швидкість обчислень.
   * **Створення через `.apply()`:** Застосовує звичайну Python-функцію послідовно до кожного елемента чи рядка стовпця за допомогою внутрішнього циклу Python. Це працює повільніше за векторизовані формули, але дозволяє реалізовувати довільну складну логіку (наприклад, з кількома умовами `if-elif-else`), яку важко записати однією математичною виразом.